### PR TITLE
[BUGFIX] Set only the fields of CallMsg required for each tx type 

### PR DESCRIPTION
**Pull request by siburu**

### CODE REVIEW

**Comment by bluele** [comment]
Does this fix https://github.com/datachainlab/ethereum-ibc-relay-chain/issues/41? @siburu

**Comment by siburu** [comment]
@bluele Sorry, but no. I'm still investigating that.

**Comment by siburu** [comment]
@bluele Now this PR is ready for review.
I confirmed that this fixes #41through this work https://github.com/datachainlab/yui-relayer-build/pull/26

**Review by bluele — APPROVED** [review]
@siburu LGTM👍

**Pull request merged**
